-- MySQL Script generated by MySQL Workbench
-- Fri Oct 19 17:10:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_condominio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_condominio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_condominio` DEFAULT CHARACTER SET utf8 ;
USE `db_condominio` ;

-- -----------------------------------------------------
-- Table `db_condominio`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`imagens` (
  `id` INT NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`morador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`morador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `is_adm` TINYINT NOT NULL,
  `avatar` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`condominio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_morador` INT NOT NULL,
  `logo` INT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `num` INT NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cnpj` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`moradia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`moradia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_condominio` INT NOT NULL,
  `id_morador` INT NOT NULL,
  `num` INT NOT NULL,
  `tipo` VARCHAR(255) NULL,
  `bloco` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`categoria_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`categoria_local` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `img` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`local` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_condominio` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `limite` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`local_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`local_img` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_local` INT NULL,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`banco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `agencia` INT NOT NULL,
  `conta` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`boleto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_morador` INT NOT NULL,
  `id_banco` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `data_vencimento` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `data_process` VARCHAR(10) NOT NULL,
  `cod` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_condominio`.`locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_condominio`.`locacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_local` INT NOT NULL,
  `id_boleto` INT NOT NULL,
  `id_morador` INT NOT NULL,
  `data` DATE NOT NULL,
  `inicio` TIME NOT NULL,
  `fim` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
